name: Build Executable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PyQt5

      - name: Build executables
        shell: pwsh
        run: |
          Get-ChildItem -Path . -Filter *.py | ForEach-Object {
            pyinstaller --onefile --noconsole --distpath . $_.Name
          }

      - name: Upload executables
        uses: actions/upload-artifact@v4
        with:
          name: executables
          path: "*.exe"

      - name: Show download link
        run: echo "Download the executables at https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}#artifacts"
